routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => 'forcehttps', 'middleware' => 'redirect503'], function() {
    Route::get('/', function () {
    /*    return bcrypt('alkalima');*/
        return view('welcome');
    });

    Route::get('/terms-and-conditions', function () {
        return view('terms-and-conditions');
    });

    Route::get('/privacy-policy', function () {
        return view('privacy-policy');
    });

    // Auth::routes();
    Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::post('/login', 'Auth\LoginController@login');
    Route::post('/login/check', 'Auth\LoginController@check');

    Route::get('/register', 'Auth\RegisterController@register')->name('register');
    Route::get('/register/{token}', 'Auth\RegisterController@newuser')->name('register.newuser');
    Route::post('/register', 'Auth\RegisterController@store')->name('register');
    Route::post('/register/setpassword', 'Auth\RegisterController@setpassword')->name('register.setpassword');
    Route::post('/register/check', 'Auth\LoginController@regcheck');

    Route::post('passwords/reset', 'Auth\ForgotPasswordController@reset')->name('passwords.reset');
    Route::resource('passwords', 'Auth\ForgotPasswordController');

    Route::get('user/login/{id}', 'UserController@login')->name('user.login');
    Route::get('phplist', 'CronController@phplist')->name('phplist');

    Route::group(['middleware' => 'auth'], function() {
        
        Route::get('patient_list', 'DashboardController@showPatientList')->name('dashboard.patient_list');
        Route::get('upcoming_birthdays', 'DashboardController@showUpcomingBirthdays')->name('dashboard.upcoming_birthdays');
        Route::post('dashboard/searchpatient', 'DashboardController@search')->name('dashboard.search');
        Route::get('dashboard/view_appointment', 'DashboardController@viewAppointment')->name('dashboard.view_appointment');
        Route::resource('dashboard', 'DashboardController');

        // appointment routes
        Route::get('appointment/create/{id}', 'AppointmentController@create');
        Route::get('appointment/viewby', 'AppointmentController@viewby')->name('appointment.viewby');
        Route::resource('appointment', 'AppointmentController');

        // patient routes
        Route::get('patient/generatepdf/{patient_id}', 'PatientController@generatePDF')->name('patient.generatepdf');
        Route::post('patient/sort', 'PatientController@sortorder')->name('patient.sort');
        Route::post('patient/medical_history', 'PatientController@medicalHistory')->name('patient.medicalhistory');
        Route::post('patient/search', 'PatientController@search')->name('patient.search');
        Route::resource('patient', 'PatientController');

        // dental chart routes
        Route::get('dentalchart/editnote/{id}/{patient_id}/{chart_name}', 'DentalChartController@editnote')->name('dentalchart.editnote');

        // dental note routes
        Route::resource('dentalnote', 'DentalNoteController');

        // dental photo routes
        Route::resource('dentalphotos', 'DentalphotoController');

        // payment routes
        Route::get('payments/create/{id}', 'PaymentController@create')->name('payment.create');
        Route::get('revenues', 'PaymentController@showRevenues')->name('payments.revenues');
        Route::post('revenues', 'PaymentController@filterRevenues')->name('payments.revenues');
        Route::resource('payments', 'PaymentController');

        // installment balance routes
        Route::get('installments/create/{id}', 'InstallmentBalanceController@create')->name('installment.create');
        Route::resource('installments', 'InstallmentBalanceController');

        // devices routes
        Route::resource('devices', 'DevicesController');

        // feedback routes
        Route::resource('feedback', 'FeedbackController');

        // user routes
        Route::get('user/roleedit/{id}', 'UserController@roleedit')->name('user.roleedit');
        Route::get('user/roledelete/{id}', 'UserController@roledelete')->name('user.roledelete');
        Route::get('user/edituser/{id}', 'UserController@edituser')->name('user.edituser');
        Route::post('user/storerole', 'UserController@storerole')->name('user.storerole');
        Route::post('user/storeuser', 'UserController@storeuser')->name('user.storeuser');
        Route::resource('user', 'UserController');

        // menu rotues
        Route::resource('menu', 'MenuController');

        // permission routes
        Route::resource('permission', 'PermissionController');
    });
});

Route::get('imagepath', 'Auth\LoginController@imagePath')->name('api.getdata');
Route::group(['middleware' => 'cors'], function() {
// Api routes
    Route::get('api/getdata/{apikey}', 'ApiController@getdata')->name('api.getdata');
    Route::get('api/postdata/{apikey}', 'ApiController@postdata')->name('api.postdata');
    Route::get('api/savedata/{apikey}', 'ApiController@savedata')->name('api.savedata');
    Route::get('api/check_connection/{apikey}/{sync_version}/{device_number}', 'ApiController@checkDeviceConnection')->name('api.check_connection');
    Route::get('api/logout_device/{apikey}/{device_number}', 'ApiController@logoutDevice')->name('api.logout_device');
    Route::post('api/get_app_data/{apikey}', 'ApiController@getAppData')->name('api.get_app_data');
    Route::get('api/get_web_data/{apikey}/{sync_version}/{device_number}/{timestamp}', 'ApiController@getWebData')->name('api.get_web_data');
    Route::get('api/redeemed/{uuid}', 'ApiController@checkRedeemed')->name('api.redeemed');
    Route::get('api/get_web_data/{apikey}/{sync_version}/{device_number}/{timestamp}', 'ApiController@getWebData')->name('api.get_web_data');

    Route::post('api/uploadjson/{apikey}', 'ApiController@uploadJsonFile')->name('api.jsonfile');
    Route::post('api/testupload', 'ApiController@testUpload')->name('api.testupload');
    Route::post('api/upload_images/{apikey}/{prefix}/{id}/{name}', 'ApiController@uploadImages')->name('api.test');
    Route::post('api/register', 'ApiController@registerUser')->name('api.register');
    Route::post('api/pre_register', 'ApiController@preRegister')->name('api.pre_register');
    Route::post('api/save_password', 'ApiController@savePassword')->name('api.save_password');
    Route::post('api/change_password', 'ApiController@changePassword')->name('api.change_password');
    Route::post('api/save-profile', 'ApiController@saveProfile')->name('api.save-profile');
    Route::get('api/get-connected-devices', 'ApiController@getConnectedDevices')->name('api.get-connected-devices');
    //Route::post('api/email-exist-options', 'ApiController@emailExistOptions')->name('api.email-exist-options');
    Route::get('api/reset-to-free-version', 'ApiController@resetToFreeVersion')->name('api.reset-to-free-version');
    Route::get('api/forgot-app-password', 'ApiController@forgotAppPassword')->name('api.forgot-app-password');
    Route::post('api/forgot-app-password-reset', 'ApiController@forgotAppPasswordReset')->name('api.forgot-app-password-reset');
    Route::post('api/forgot-app-password-retrieve-code', 'ApiController@forgotAppPasswordRetrieveCode')->name('api.forgot-app-password-retrieve-code');
    Route::post('api/retrieve', 'ApiController@retrieveCode')->name('api.retrieve');
    Route::post('api/get_app_data/{apikey}', 'ApiController@getAppData')->name('api.get_app_data');

    
    Route::get('api/check-cloud-data/{apikey}', 'ApiController@checkCloudData')->name('api.check-cloud-data');
    Route::get('api/set-main-device/{apikey}', 'ApiController@setMainDevice')->name('api.set-main-device');
    Route::get('api/set-data-to-reset/{apikey}', 'ApiController@setDataToReset')->name('api.set-data-to-reset');
    Route::get('api/check-for-reset-data/{apikey}', 'ApiController@checkForResetData')->name('api.check-for-reset-data');
    Route::post('api/save-restore-backup/{apikey}', 'ApiController@saveRestoreBackup')->name('api.save-restore-backup');
});
// Route::resource('redeem', 'RedeemController');

resources/views/installments/create.blade.php
@extends('layouts/default')
@section('content')
<section class="content-header">
	<h1>&nbsp;</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-gear"></i> Patients</a></li>
		<li class="active"><a href="#">Payments</a></li>
	</ol>
</section>
<section class="content">
	<div class="box box-primary">
		<div class="box-header with-border">
			<h3 class="box-title"><span class="fa fa-info"></span> &nbsp;Patient Information</h3>
		</div>
		<div class="box-body">
			<div class="pull-left image">
	          	@if($patient->image)
	          		@if(\File::exists($patient->image))
	          			{!! HTML::image($patient->image, '', ['class'=>'img-circle list-image']) !!}
	          		@else
	          			{!! HTML::image('uploads/patients/'.$patient->image, '', ['class'=>'img-circle list-image']) !!}
	        		@endif
	        	@else
	        		{!! HTML::image('uploads/no_pic.jpg', '', ['class'=>'img-circle','style'=>'height:65px;width:65px']) !!}
	        	@endif
	        </div>
	        <div class="pull-left info" style="padding-left:15px">
	        	<p style="font-size:16px !important">
	        		<b>{{ $patient->first_name.' '.$patient->last_name }}</b><br>
	        		{{ $patient->contact_number }}<br>
	        		{{ $patient->address }}<br>
	        		{{ \Carbon\Carbon::parse($patient->birthdate)->format('F d, Y').' - '.\Carbon\Carbon::parse($patient->birthdate)->age.' years old' }}
	        	</p>
	        </div>
	        <div class="pull-right">
	        	<a href="{{ route('patient.show', \Hashids::encode($patient->id)) }}" class="btn btn-primary btn-sm"><span class="fa fa-user"></span> &nbsp;Patient Info</a>
	        </div>
		</div>
	</div>
	<div class="box box-primary">
		<div class="box-body">
			{!! Form::open(['route'=>'installments.store','id'=>'installmentsform']) !!}
			<div class="form-group" id="dateField">
				<label>Date</label>
				<div class="input-group">
			        <div class="input-group-addon" style="padding:0 10px 0 10px">
			        	<i class="fa fa-calendar"></i>
			        </div>
					{!! Form::text('date', null, ['id'=>'date','class'=>'form-control datemask']) !!}
				</div>
				<div id="dateInput" style="font-size:11px; color:#dd4b39"></div>
			</div>
			<div class="form-group" id="amountField">
				<label>Amount</label>
				{!! Form::text('amount', null, ['class'=>'form-control','id'=>'amount']) !!}
				<div id="amountInput" style="font-size:11px; color:#dd4b39"></div>
			</div>
			<div class="form-group" id="remarksField">
				<label>Remarks</label>
				{!! Form::textarea('remarks', null, ['class'=>'form-control','id'=>'remarks','style'=>'height:100px;resize:none']) !!}
				<div id="remarksInput" style="font-size:11px; color:#dd4b39"></div>
			</div>
			<div class="form-group">
				{!! Form::hidden('payment_id', $payment->id) !!}
				{!! Form::hidden('patient_id', $patient->id) !!}
				{!! Form::hidden('original_amount', 0) !!}
				{!! Form::button('Save Installment',['class'=>'btn btn-primary btn-flat btn-sm','id'=>'saveinstallmentbtn']) !!}
			</div>
		</div>
	</div>
</section>
@endsection

@section('js')
{!! HTML::script('library/input-mask/jquery.inputmask.js') !!}
{!! HTML::script('library/input-mask/jquery.inputmask.date.extensions.js') !!}
{!! HTML::script('library/input-mask/jquery.inputmask.extensions.js') !!}
<script type="text/javascript">
	<?php if(\Session::has('status')){ ?>
		swal("<?php echo \Session::get('status'); ?>", "", "error");  
	<?php } ?>

	$('#installmentsform').on('submit', function(){
		ga('send', 'event', '<?php echo \Auth::user()->email; ?>', 'Add', 'Add Patient Installment');
	});

	$(".datemask").inputmask("mm/dd/yyyy", {"placeholder": "mm/dd/yyyy"});
	$('#amount').keydown(function (event) {
        if (event.shiftKey == true) {
            event.preventDefault();
        }
        if ((event.keyCode >= 48 && event.keyCode <= 57) || 
            (event.keyCode >= 96 && event.keyCode <= 105) || 
            event.keyCode == 8 || event.keyCode == 9 || event.keyCode == 37 ||
            event.keyCode == 39 || event.keyCode == 46 || event.keyCode == 190) {
        } else {
            event.preventDefault();
        }
        if($(this).val().indexOf('.') !== -1 && event.keyCode == 190)
            event.preventDefault(); 
    });

    $('#saveinstallmentbtn').click(function() {
    	if($('#date').val()==''){
			$('#dateField').addClass('has-error');
		    $('#dateInput').html('<i class="fa fa-times-circle-o"></i> Date is Required.');
		    $('#date').focus();
		    return false;
		} else if($('#amount').val()==''){
			$('#amountField').addClass('has-error');
		    $('#amountInput').html('<i class="fa fa-times-circle-o"></i> Amount is Required.');
		    $('#amount').focus();
		    return false;
		} else if($('#remarks').val()==''){
			$('#remarksField').addClass('has-error');
		    $('#remarksInput').html('<i class="fa fa-times-circle-o"></i> Remarks is Required.');
		    $('#remarks').focus();
		    return false;
		} else {
			$('#saveinstallmentbtn').attr('disabled', 'disabled');
			$('#saveinstallmentbtn').html('<span class="fa fa-spinner fa-spin"></span> Processing...');
			$('#installmentsform').submit();
		}
    });
</script>
@endsection

resources/views/installments/edit.blade.php
@extends('layouts/default')
@section('content')
<section class="content-header">
	<h1>&nbsp;</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-gear"></i> Patients</a></li>
		<li class="active"><a href="#">Payments</a></li>
	</ol>
</section>
<section class="content">
	<div class="box box-primary">
		<div class="box-header with-border">
			<h3 class="box-title"><span class="fa fa-info"></span> &nbsp;Patient Information</h3>
		</div>
		<div class="box-body">
			<div class="pull-left image">
	          	@if($patient->image)
	          		@if(\File::exists($patient->image))
	          			{!! HTML::image($patient->image, '', ['class'=>'img-circle list-image']) !!}
	          		@else
	          			{!! HTML::image('uploads/patients/'.$patient->image, '', ['class'=>'img-circle list-image']) !!}
	        		@endif
	        	@else
	        		{!! HTML::image('uploads/no_pic.jpg', '', ['class'=>'img-circle','style'=>'height:65px;width:65px']) !!}
	        	@endif
	        </div>
	        <div class="pull-left info" style="padding-left:15px">
	        	<p style="font-size:16px !important">
	        		<b>{{ $patient->first_name.' '.$patient->last_name }}</b><br>
	        		{{ $patient->contact_number }}<br>
	        		{{ $patient->address }}<br>
	        		{{ \Carbon\Carbon::parse($patient->birthdate)->format('F d, Y').' - '.\Carbon\Carbon::parse($patient->birthdate)->age.' years old' }}
	        	</p>
	        </div>
	        <div class="pull-right">
	        	<a href="{{ route('patient.show', \Hashids::encode($patient->id)) }}" class="btn btn-primary btn-sm"><span class="fa fa-user"></span> &nbsp;Patient Info</a>
	        </div>
		</div>
	</div>
	<div class="box box-primary">
		<div class="box-body">
			{!! Form::open(['route'=>['installments.update',\Hashids::encode($installments->id)],'method'=>'PUT','id'=>'installmentsform']) !!}
			<div class="form-group" id="dateField">
				<label>Date</label>
				<div class="input-group">
			        <div class="input-group-addon" style="padding:0 10px 0 10px">
			        	<i class="fa fa-calendar"></i>
			        </div>
					{!! Form::text('date', isset($installments->date) ? $installments->date : null, ['id'=>'date','class'=>'form-control datemask']) !!}
				</div>
				<div id="dateInput" style="font-size:11px; color:#dd4b39"></div>
			</div>
			<div class="form-group" id="amountField">
				<label>Amount</label>
				{!! Form::text('amount', $installments->amount, ['class'=>'form-control','id'=>'amount']) !!}
				<div id="amountInput" style="font-size:11px; color:#dd4b39"></div>
			</div>
			<div class="form-group" id="remarksField">
				<label>Remarks</label>
				{!! Form::textarea('remarks', $installments->remarks, ['class'=>'form-control','id'=>'remarks','style'=>'height:100px;resize:none']) !!}
				<div id="remarksInput" style="font-size:11px; color:#dd4b39"></div>
			</div>
			<div class="form-group">
			{!! Form::hidden('payment_id', $payment->id) !!}
			{!! Form::hidden('patient_id', $patient->id) !!}
			{!! Form::hidden('original_amount', $installments->amount) !!}
				{!! Form::button('Save Installment',['class'=>'btn btn-primary btn-flat btn-sm','id'=>'saveinstallmentbtn']) !!}
			</div>
		</div>
	</div>
</section>
@endsection

@section('js')
{!! HTML::script('library/input-mask/jquery.inputmask.js') !!}
{!! HTML::script('library/input-mask/jquery.inputmask.date.extensions.js') !!}
{!! HTML::script('library/input-mask/jquery.inputmask.extensions.js') !!}
<script type="text/javascript">
	<?php if(\Session::has('status')){ ?>
		swal("<?php echo \Session::get('status'); ?>", "", "error");  
	<?php } ?>

	$(".datemask").inputmask("mm/dd/yyyy", {"placeholder": "mm/dd/yyyy"});
	$('#amount').keydown(function (event) {
        if (event.shiftKey == true) {
            event.preventDefault();
        }
        if ((event.keyCode >= 48 && event.keyCode <= 57) || 
            (event.keyCode >= 96 && event.keyCode <= 105) || 
            event.keyCode == 8 || event.keyCode == 9 || event.keyCode == 37 ||
            event.keyCode == 39 || event.keyCode == 46 || event.keyCode == 190) {
        } else {
            event.preventDefault();
        }
        if($(this).val().indexOf('.') !== -1 && event.keyCode == 190)
            event.preventDefault(); 
    });

    $('#saveinstallmentbtn').click(function() {
    	if($('#date').val()==''){
			$('#dateField').addClass('has-error');
		    $('#dateInput').html('<i class="fa fa-times-circle-o"></i> Date is Required.');
		    $('#date').focus();
		    return false;
		} else if($('#amount').val()==''){
			$('#amountField').addClass('has-error');
		    $('#amountInput').html('<i class="fa fa-times-circle-o"></i> Amount is Required.');
		    $('#amount').focus();
		    return false;
		} else if($('#remarks').val()==''){
			$('#remarksField').addClass('has-error');
		    $('#remarksInput').html('<i class="fa fa-times-circle-o"></i> Remarks is Required.');
		    $('#remarks').focus();
		    return false;
		} else {
			$('#saveinstallmentbtn').attr('disabled', 'disabled');
			$('#saveinstallmentbtn').html('<span class="fa fa-spinner fa-spin"></span> Processing...');
			$('#installmentsform').submit();
		}
    });
</script>
@endsection

resources/views/installments/show.blade.php
@extends('layouts/default')
@section('content')
<section class="content-header">
	<h1>&nbsp;</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-gear"></i> Payments</a></li>
		<li class="active"><a href="#">Installment Payments</li>
	</ol>
</section>
<section class="content">
	<div class="box box-primary" style="color:#444">
		<div class="box-header with-border">
			<h3 class="box-title"><span class="fa fa-info"></span> &nbsp;Patient Information</h3>
		</div>
		<div class="box-body">
			<div class="pull-left image">
	          	@if($patient->image)
	          		@if(\File::exists($patient->image))
	          			{!! HTML::image($patient->image, '', ['class'=>'img-circle list-image']) !!}
	          		@else
	          			{!! HTML::image('uploads/patients/'.$patient->image, '', ['class'=>'img-circle list-image']) !!}
	        		@endif
	        	@else
	        		{!! HTML::image('uploads/no_pic.jpg', '', ['class'=>'img-circle','style'=>'height:65px;width:65px']) !!}
	        	@endif
	        </div>
	        <div class="pull-left info" style="padding-left:15px;color:#444">
	        	<p style="font-size:16px !important">
	        		<b>{{ $patient->full_name }}</b><br>
	        		{{ $patient->contact_number }}<br>
	        		{{ $patient->address }}<br>
	        		{{ \Carbon\Carbon::parse($patient->birthdate)->format('F d, Y').' - '.\Carbon\Carbon::parse($patient->birthdate)->age.' years old' }}
	        	</p>
	        </div>
	        <div class="pull-right">
	        	<a href="{{ url('patient', \Hashids::encode($patient->id)) }}" class="btn btn-primary btn-sm"><span class="fa fa-user"></span> &nbsp;Patient Info</a>
	        </div>
		</div>
	</div>
	<div class="box box-primary" style="color:#444">
		<div class="box-header with-border">
			<h3 class="box-title"><span class="fa fa-credit-card"></span> &nbsp;Installment Payments</h3>
		</div>
		<div class="box-body">
	        <table class="table table-hover">
				<thead>
					<th></th>
					<th></th>
				</thead>
				<tbody>
					<tr>
						<td style="width:30%">
							<b>Total amount</b><br>
							<b>Amount paid</b><br>
							<b>Balance</b>
						</td>
						<td style="width:30%">
							{{ $payment->amount.' '.\Auth::user()->currency }}<br>
							{{ $amount_paid->totalamount.' '.\Auth::user()->currency }}<br>
							{{ $payment->amount - $amount_paid->totalamount.' '.\Auth::user()->currency }}
						</td>
						<td style="width:40%" align="right">
							<a href="{{ url('installments/create', \Hashids::encode($payment->id)) }}" class="btn btn-primary btn-sm"><span class="fa fa-plus"></span> &nbsp;Add Payment</a>
							<a href="{{ url('payments', \Hashids::encode($payment->id)) }}/edit" class="btn btn-primary btn-sm"><span class="fa fa-pencil"></span> &nbsp;Edit Payable</a>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div class="box box-primary" style="color:#444">

		<div class="box-body">
			<table class="table table-hover" id="tableinstallment">
				<thead>
					<th></th>
					<th></th>
					<th></th>
				</thead>
				<tbody>
					@if(count($installments))
					@foreach($installments as $key => $installment)
					<tr>
						<td style="vertical-align:middle; width:3%">{{ ($installments->currentpage()-1) * $installments->perpage() + $key + 1 }}</td>
						<td style="width:20%">
							<b>Date</b><br>
							<b>Amount</b><br>
							<b>Remarks</b>
						</td>
						<td style="width:40%">
							{{ \Carbon\Carbon::parse($installment->date)->format('M d, Y') }}<br>
							{{ $installment->amount.' '.\Auth::user()->currency }}<br>
							{{ $installment->remarks }}
						</td>
						<td style="width:10%" align="right">
							<a href="{{ url('installments', \Hashids::encode($installment->id)) }}/edit" class="btn btn-primary btn-xs"><span class="fa fa-pencil"></span></a>
							<a onclick="deletepayment({{ $installment->id }})" class="btn btn-primary btn-xs"><span class="fa fa-trash"></span></a>
						</td>
					</tr>
					@endforeach
					@else
					<tr>
						<td>No payments has been made yet.</td>
					</tr>
					@endif
				</tbody>
			</table>
			<div class="pull-right">{!! (count($installments)) ? $installments->render() : '' !!}</div>
		</div>
	</div>
</section>
@endsection

@section('js')
<script type="text/javascript">
ga('send', 'installments_list');

<?php if(\Session::has('status')){ ?>
	swal("<?php echo \Session::get('status'); ?>", "", "success");  
<?php } ?>

function deletepayment(id){
	swal({   
		title: "Are you sure?",   
		text: "You will not be able to recover this Payment!",   
		type: "warning",   
		showCancelButton: true,   
		confirmButtonColor: "#DD6B55",   
		confirmButtonText: "Yes, delete it!",   
		closeOnConfirm: false,
		showLoaderOnConfirm: true 
	}, 
	function(){  
		ga('send', 'event', '<?php echo \Auth::user()->email; ?>', 'Delete', 'Delete Patient Installment');
		$.ajax({
			url: base_url+'/installments/'+id,
			type: 'DELETE',
			success: function(result){
				setTimeout(function(){  
					swal("Deleted!", "Payment has been deleted.", "success"); 
					location.reload();
				}, 3000);
			}
		});
	});
}

</script>
@endsection