routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => 'forcehttps', 'middleware' => 'redirect503'], function() {
    Route::get('/', function () {
    /*    return bcrypt('alkalima');*/
        return view('welcome');
    });

    Route::get('/terms-and-conditions', function () {
        return view('terms-and-conditions');
    });

    Route::get('/privacy-policy', function () {
        return view('privacy-policy');
    });

    // Auth::routes();
    Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::post('/login', 'Auth\LoginController@login');
    Route::post('/login/check', 'Auth\LoginController@check');

    Route::get('/register', 'Auth\RegisterController@register')->name('register');
    Route::get('/register/{token}', 'Auth\RegisterController@newuser')->name('register.newuser');
    Route::post('/register', 'Auth\RegisterController@store')->name('register');
    Route::post('/register/setpassword', 'Auth\RegisterController@setpassword')->name('register.setpassword');
    Route::post('/register/check', 'Auth\LoginController@regcheck');

    Route::post('passwords/reset', 'Auth\ForgotPasswordController@reset')->name('passwords.reset');
    Route::resource('passwords', 'Auth\ForgotPasswordController');

    Route::get('user/login/{id}', 'UserController@login')->name('user.login');
    Route::get('phplist', 'CronController@phplist')->name('phplist');

    Route::group(['middleware' => 'auth'], function() {
        
        Route::get('patient_list', 'DashboardController@showPatientList')->name('dashboard.patient_list');
        Route::get('upcoming_birthdays', 'DashboardController@showUpcomingBirthdays')->name('dashboard.upcoming_birthdays');
        Route::post('dashboard/searchpatient', 'DashboardController@search')->name('dashboard.search');
        Route::get('dashboard/view_appointment', 'DashboardController@viewAppointment')->name('dashboard.view_appointment');
        Route::resource('dashboard', 'DashboardController');

        // appointment routes
        Route::get('appointment/create/{id}', 'AppointmentController@create');
        Route::get('appointment/viewby', 'AppointmentController@viewby')->name('appointment.viewby');
        Route::resource('appointment', 'AppointmentController');

        // patient routes
        Route::get('patient/generatepdf/{patient_id}', 'PatientController@generatePDF')->name('patient.generatepdf');
        Route::post('patient/sort', 'PatientController@sortorder')->name('patient.sort');
        Route::post('patient/medical_history', 'PatientController@medicalHistory')->name('patient.medicalhistory');
        Route::post('patient/search', 'PatientController@search')->name('patient.search');
        Route::resource('patient', 'PatientController');

        // dental chart routes
        Route::get('dentalchart/editnote/{id}/{patient_id}/{chart_name}', 'DentalChartController@editnote')->name('dentalchart.editnote');

        // dental note routes
        Route::resource('dentalnote', 'DentalNoteController');

        // dental photo routes
        Route::resource('dentalphotos', 'DentalphotoController');

        // payment routes
        Route::get('payments/create/{id}', 'PaymentController@create')->name('payment.create');
        Route::get('revenues', 'PaymentController@showRevenues')->name('payments.revenues');
        Route::post('revenues', 'PaymentController@filterRevenues')->name('payments.revenues');
        Route::resource('payments', 'PaymentController');

        // installment balance routes
        Route::get('installments/create/{id}', 'InstallmentBalanceController@create')->name('installment.create');
        Route::resource('installments', 'InstallmentBalanceController');

        // devices routes
        Route::resource('devices', 'DevicesController');

        // feedback routes
        Route::resource('feedback', 'FeedbackController');

        // user routes
        Route::get('user/roleedit/{id}', 'UserController@roleedit')->name('user.roleedit');
        Route::get('user/roledelete/{id}', 'UserController@roledelete')->name('user.roledelete');
        Route::get('user/edituser/{id}', 'UserController@edituser')->name('user.edituser');
        Route::post('user/storerole', 'UserController@storerole')->name('user.storerole');
        Route::post('user/storeuser', 'UserController@storeuser')->name('user.storeuser');
        Route::resource('user', 'UserController');

        // menu rotues
        Route::resource('menu', 'MenuController');

        // permission routes
        Route::resource('permission', 'PermissionController');
    });
});

Route::get('imagepath', 'Auth\LoginController@imagePath')->name('api.getdata');
Route::group(['middleware' => 'cors'], function() {
// Api routes
    Route::get('api/getdata/{apikey}', 'ApiController@getdata')->name('api.getdata');
    Route::get('api/postdata/{apikey}', 'ApiController@postdata')->name('api.postdata');
    Route::get('api/savedata/{apikey}', 'ApiController@savedata')->name('api.savedata');
    Route::get('api/check_connection/{apikey}/{sync_version}/{device_number}', 'ApiController@checkDeviceConnection')->name('api.check_connection');
    Route::get('api/logout_device/{apikey}/{device_number}', 'ApiController@logoutDevice')->name('api.logout_device');
    Route::post('api/get_app_data/{apikey}', 'ApiController@getAppData')->name('api.get_app_data');
    Route::get('api/get_web_data/{apikey}/{sync_version}/{device_number}/{timestamp}', 'ApiController@getWebData')->name('api.get_web_data');
    Route::get('api/redeemed/{uuid}', 'ApiController@checkRedeemed')->name('api.redeemed');
    Route::get('api/get_web_data/{apikey}/{sync_version}/{device_number}/{timestamp}', 'ApiController@getWebData')->name('api.get_web_data');

    Route::post('api/uploadjson/{apikey}', 'ApiController@uploadJsonFile')->name('api.jsonfile');
    Route::post('api/testupload', 'ApiController@testUpload')->name('api.testupload');
    Route::post('api/upload_images/{apikey}/{prefix}/{id}/{name}', 'ApiController@uploadImages')->name('api.test');
    Route::post('api/register', 'ApiController@registerUser')->name('api.register');
    Route::post('api/pre_register', 'ApiController@preRegister')->name('api.pre_register');
    Route::post('api/save_password', 'ApiController@savePassword')->name('api.save_password');
    Route::post('api/change_password', 'ApiController@changePassword')->name('api.change_password');
    Route::post('api/save-profile', 'ApiController@saveProfile')->name('api.save-profile');
    Route::get('api/get-connected-devices', 'ApiController@getConnectedDevices')->name('api.get-connected-devices');
    //Route::post('api/email-exist-options', 'ApiController@emailExistOptions')->name('api.email-exist-options');
    Route::get('api/reset-to-free-version', 'ApiController@resetToFreeVersion')->name('api.reset-to-free-version');
    Route::get('api/forgot-app-password', 'ApiController@forgotAppPassword')->name('api.forgot-app-password');
    Route::post('api/forgot-app-password-reset', 'ApiController@forgotAppPasswordReset')->name('api.forgot-app-password-reset');
    Route::post('api/forgot-app-password-retrieve-code', 'ApiController@forgotAppPasswordRetrieveCode')->name('api.forgot-app-password-retrieve-code');
    Route::post('api/retrieve', 'ApiController@retrieveCode')->name('api.retrieve');
    Route::post('api/get_app_data/{apikey}', 'ApiController@getAppData')->name('api.get_app_data');

    
    Route::get('api/check-cloud-data/{apikey}', 'ApiController@checkCloudData')->name('api.check-cloud-data');
    Route::get('api/set-main-device/{apikey}', 'ApiController@setMainDevice')->name('api.set-main-device');
    Route::get('api/set-data-to-reset/{apikey}', 'ApiController@setDataToReset')->name('api.set-data-to-reset');
    Route::get('api/check-for-reset-data/{apikey}', 'ApiController@checkForResetData')->name('api.check-for-reset-data');
    Route::post('api/save-restore-backup/{apikey}', 'ApiController@saveRestoreBackup')->name('api.save-restore-backup');
});
// Route::resource('redeem', 'RedeemController');

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>My Dental Clinic</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <meta name="csrf-token" content="{{ csrf_token() }}" />
  <link rel="shortcut icon" href="{{ url('uploads/favicon.ico') }}" type="image/x-icon">
  <link rel="icon" href="{{ url('uploads/favicon.ico') }}" type="image/x-icon">
  {!! HTML::style('css/bootstrap.css') !!}
  {!! HTML::style('css/font-awesome.min.css') !!}
  {!! HTMl::style('css/ionicons.min.css') !!}
  {!! HTML::style('library/datatables/dataTables.bootstrap.css') !!}
  {!! HTML::style('css/style.css') !!}
  {!! HTML::style('css/skins/_all-skins.css') !!}
  {!! HTMl::style('library/datepicker/datepicker3.css') !!}
  {!! HTML::style('library/multiupload/jquery-ui.css') !!}
  {!! HTMl::style('library/sweetalert/sweetalert.css') !!}
  @yield('css')
  <style type="text/css">
  .ui-datepicker-month {
    -moz-z-index: 9999;
  }
  </style>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition skin-blue sidebar-mini" data-url="{{ url('/') }}">
<!-- Site wrapper -->
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="{{ url('/likod/dashboard') }}" class="logo" style="position:fixed; background-color:#196eee">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><img src="{{ url('uploads/logo-tooth.png') }}" alt="" width="30"></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><img src="{{ url('uploads/logo.png') }}" alt="" width="200"></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top" role="navigation" style="position:fixed; width:100%">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <!-- <div class="">
        <form class="navbar-form" role="search" action="{{ route('patient.search') }}" method="POST">
          <input type="hidden" name="_token" value="{{ csrf_token() }}" />
          <div class="form-group">
            <input type="text" class="form-control" id="navbar-search-input" placeholder="Search Patient Name" style="width:300px;background-color:#fff" name="patient_name" value="{{ isset($patient_name) ? $patient_name : '' }}">
          </div>
        </form>
      </div> -->
    </nav>
  </header>

  <aside class="main-sidebar" style="position:fixed">
    <section class="sidebar">
      <ul class="sidebar-menu">
        <li class="header" style="color:#fff"><h5>{{ \Auth::guard('admin')->user()->first_name.' '.\Auth::guard('admin')->user()->last_name }} </h5></li>
        <li><a href="{{ route('likod.dashboard.index') }}"><i class="fa fa-home"></i><span>Home</span></a></li>
        <li><a href="{{ route('admin.dentist') }}"><i class="fa fa-user"></i><span>Dentist</span></a></li>
        <li><a href="{{ route('admin.patient') }}"><i class="fa fa-group"></i><span>Patients</span></a></li>
        <li><a href="{{ route('admin.stats') }}"><i class="fa fa-bar-chart"></i><span>Stats</span></a></li>
        <!-- <li class="treeview">
          <a href="#">
            <i class="fa fa-calendar-o"></i>
            <span>Appointments</span>
            <i class="fa fa-angle-right pull-right"></i>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{ route('patient_appointment.create') }}"><i class="fa fa-circle-o"></i> Add Appointment</a></li>
            <li><a href="{{ route('patient_appointment.index') }}"><i class="fa fa-circle-o"></i> Appointment's List</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-group"></i>
            <span>Patients</span>
            <i class="fa fa-angle-right pull-right"></i>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{ route('patient.create') }}"><i class="fa fa-circle-o"></i> Add Patient</a></li>
            <li><a href="{{ route('patient.index') }}"><i class="fa fa-circle-o"></i> Patient's List</a></li>
          </ul>
        </li>
        <li><a href="{{ route('user.edit', \Hashids::encode(\Auth::guard('admin')->user()->id)) }}"><i class="fa fa-gear"></i><span>Settings</span></a></li>
        <li><a href="{{ route('feedback.create') }}"><i class="fa fa-envelope"></i><span>Feedback</span></a></li> -->
        <!-- <li><a href="#"><i class="fa fa-lock"></i><span>Unlock Features</span></a></li> -->
        <li><a href="{{ route('admin.logout') }}"><i class="fa fa-sign-out"></i><span>Sign Out</span></a></li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" style="padding-top:40px">
    @yield('content')
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="container" style="max-height:20px">
      <div class="pull-right hidden-xs">
        <b>Version</b> 1.0
      </div>
      <strong>Copyright &copy; 2016 <a href="#">Quantum X</a>.</strong> All rights reserved.
    </div><!-- /.container -->
  </footer>
</div>
{!! HTML::script('js/jquery.js') !!}
{!! HTML::script('library/multiupload/jquery-ui.min.js') !!}
{!! HTML::script('js/bootstrap.js') !!}
{!! HTML::script('library/select2/select2.full.min.js') !!}
{!! HTML::script('js/jquery.slimscroll.js') !!}
{!! HTML::script('library/iCheck/icheck.min.js') !!}
{!! HTML::script('js/fastclick.js') !!}
{!! HTML::script('js/app.js') !!}
{!! HTML::script('library/datatables/jquery.dataTables.min.js') !!}
{!! HTML::script('library/datatables/dataTables.bootstrap.min.js') !!}
{!! HTML::script('library/sweetalert/sweetalert-dev.js') !!}
<script type="text/javascript">
  var base_url = $('body').attr('data-url');
  $.ajaxSetup({
    headers: { 'X-CSRF-Token' : $('meta[name=csrf-token]').attr('content') }
  });
</script>
<script type="text/javascript">
  // hide main menu if no sub menus
  $(function(){
      $( ".menu_dropdown" ).each(function( index ) {
          var count = $(this).find('ul.dropdown-menu').children('li').length;
          if (count != 0) {
              $(this).show();
          } else {
              $(this).hide();
          }
      });

      $('.datemask').datepicker({
        yearRange: "-1:+2",
        changeMonth: true,
        changeYear: true,
        dateFormat: "mm/dd/yyyy"
      });

      $('.fdatemask').datepicker({
        yearRange: "0:+2",
        changeMonth: true,
        changeYear: true,
        dateFormat: "mm/dd/yyyy",
        minDate: 0
      });

      $('.birthdatemask').datepicker({
        yearRange: "-50:+1",
        changeMonth: true,
        changeYear: true,
        dateFormat: "mm/dd/yyyy"
      });

  });
</script>
@yield('js')
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>